// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
    BatchActionBar: typeof import('./../components/BatchActionBar/index.vue')['default']
    Clipboard: typeof import('./../components/Clipboard/index.vue')['default']
    DatePickerQuery: typeof import('./../components/dateComponents/components/datePickerQuery.vue')['default']
    DateTimePickerQuery: typeof import('./../components/dateComponents/components/dateTimePickerQuery.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    FilterColumnControl: typeof import('./../components/FilterColumnControl/index.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    IndexOld: typeof import('./../components/staticInfo/index-old.vue')['default']
    InfoItem: typeof import('./../components/staticInfo/InfoItem.vue')['default']
    LazyImage: typeof import('./../components/LazyImage/index.vue')['default']
    LineChart: typeof import('./../components/Echart/LineChart/index.vue')['default']
    NormalImageUpload: typeof import('./../components/NormalImageUpload/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    PcasCascader: typeof import('./../components/PcasCascader/index.vue')['default']
    PromiseSwitch: typeof import('./../components/PromiseSwitch/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    StaticInfo: typeof import('./../components/staticInfo/index.vue')['default']
    SubItem: typeof import('./../components/staticInfo/subItem.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
  }
}
